<a href="https://colab.research.google.com/github/dwelle511/2025-LLM/blob/main/BDA_Day06_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 7. DataFrame 정보와 검색

In [ ]:
#데이터프레임 준비
import pandas as pd

# !git clone "https://github.com/ai7dnn/2026-1-BDA/blob/main/2016%EB%85%84%EC%A1%B8%EC%9D%8C%EC%9A%B4%EC%A0%84.csv"
# df=pf.read_csv("2016졸음운전.csv",encoding="cp949",index_col=0)
df=pd.read_csv("https://github.com/ai7dnn/2026-1-BDA/raw/refs/heads/main/2016%EB%85%84%EC%A1%B8%EC%9D%8C%EC%9A%B4%EC%A0%84.csv",encoding='cp949',index_col=0)

In [ ]:
#데이터 첫 열을 인덱스 데이터프레임의 인덱스로 상용하기 위해 옵션 index_col=0지정해 읽기
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [ ]:
df.T

연월,2016년1월,2016년2월,2016년3월,2016년4월,2016년5월,2016년6월,2016년7월,2016년8월,2016년9월,2016년10월,2016년11월,2016년12월
사고(건),192,174,217,216,239,200,227,230,187,183,200,168
사망(명),5,6,7,7,13,12,9,7,13,10,5,4
부상(명),387,328,435,419,522,362,460,490,347,367,418,364

In [ ]:
import pandas as pd
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 684.0+ bytes

In [ ]:
#df.sum() 모든 열의 합, axis=0 위에서 아래로 수직으로 합, 열의 합
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [ ]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [ ]:
df.sum(axis=1)
#df.sum(axis=1) 모든 행의 합

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [ ]:
df.cumsum(axis=1)
#df.cumsum() 누적 합, df.cumsum(axis=0) 위에서 아래로 수직으로 누적합
#df.cumsum(axis=1) 왼쪽에서 오른쪽으로 수펴응로 누적합

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [ ]:
df.mean()
#모든 열의 평균 구하기
#axis=0 따라 이동(위에서 아래로수직으로) 열의 평균
#axis=1 왼쪽에서 오른쪽으로 수평으로 평균, 모든 행의 평균 구하기
#axis=None 전체 평균

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [ ]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [ ]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [ ]:
df.max()

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [ ]:
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [ ]:
df.max(axis=None)

522

In [ ]:
df.min()

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [ ]:
df.min(axis=0)

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [ ]:
df.min(axis=None)

4

In [ ]:
df[['사망(명)','부상(명)']].sum(axois=1)

TypeError: sum() got an unexpected keyword argument 'axois'

In [ ]:
df2=df.copy()
df2['재해자수']=df[['사망(명)','부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [ ]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [ ]:
df.loc['총계']=df.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [ ]:
#불리안 인덱싱 @@@
df2>10

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True

In [ ]:
df2[df2>10] #@

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192    NaN    387   392
2016년2월     174    NaN    328   334
2016년3월     217    NaN    435   442
2016년4월     216    NaN    419   426
2016년5월     239   13.0    522   535
2016년6월     200   12.0    362   374
2016년7월     227    NaN    460   469
2016년8월     230    NaN    490   497
2016년9월     187   13.0    347   360
2016년10월    183    NaN    367   377
2016년11월    200    NaN    418   423
2016년12월    168    NaN    364   368

In [ ]:
df2[ [True]*6+[False]*7 ] #@

ValueError: Item wrong length 13 instead of 12.

In [ ]:
#조건과 isin() @@@

df2["재해자수"]>400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
Name: 재해자수, dtype: bool

In [ ]:
df2[df2['재해자수']>400]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년11월    200      5    418   423

In [ ]:
df['사망(명)']==7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
총계          False
Name: 사망(명), dtype: bool

In [ ]:
df['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
총계          False
Name: 사망(명), dtype: bool

In [ ]:
#isin(),str,contains()

df['사망(명)'].isin([7,10])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월     True
2016년11월    False
2016년12월    False
총계          False
Name: 사망(명), dtype: bool

In [ ]:
df[df['사망(명)'].isin([7,10])]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367

In [ ]:
df[(df['사망(명)'].isin([7,10]))| (df['부상(명)']>350)]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364
총계         2433     98   4899

In [ ]:
df[df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

In [ ]:
#논리 첨자로 값 대입
df3=df.copy()
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364
총계         2433     98   4899

In [ ]:
df3[df3>10]=-df3
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월    -192      5   -387
2016년2월    -174      6   -328
2016년3월    -217      7   -435
2016년4월    -216      7   -419
2016년5월    -239    -13   -522
2016년6월    -200    -12   -362
2016년7월    -227      9   -460
2016년8월    -230      7   -490
2016년9월    -187    -13   -347
2016년10월   -183     10   -367
2016년11월   -200      5   -418
2016년12월   -168      4   -364
총계        -2433    -98  -4899

In [ ]:
#함수 df.query
df=pd.DataFrame({"a":range(1,6),
                 'b':range(6,-3,-2),
                 'c':range(10,5,-1),
                 'd clmns':range(3,-2,-1),
                 'e':['python','java','python','go','python']})
df

   a  b   c  d clmns       e
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [ ]:
df

   a  b   c  d clmns       e
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [ ]:
df.query('a>b')

   a  b  c  d clmns       e
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df[df.a >df.b]

   a  b  c  d clmns       e
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
#
df.query('c==10')

   a  b   c  d clmns       e
0  1  6  10        3  python

In [ ]:
df.query('a>0')

   a  b   c  d clmns       e
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [ ]:
df.query('e=="python"')

   a  b   c  d clmns       e
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [ ]:
df.query("e !='python'")

   a  b  c  d clmns     e
1  2  4  9        2  java
3  4  0  7        0    go

In [ ]:
df.query('a==`d clmns`')

   a  b  c  d clmns     e
1  2  4  9        2  java

In [ ]:
df.query('a =="d clmns"')

Empty DataFrame
Columns: [a, b, c, d clmns, e]
Index: []

In [ ]:
df[df.a==df["d clmns"]]

   a  b  c  d clmns     e
1  2  4  9        2  java

In [ ]:
df.query('a>3 |b>8')

   a  b  c  d clmns       e
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df.query('a>2 & c<8')

   a  b  c  d clmns       e
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df.query("e in ['python','go']")

   a  b   c  d clmns       e
0  1  6  10        3  python
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [ ]:
#nu
num=3
df.query('b>@num')

   a  b   c  d clmns       e
0  1  6  10        3  python
1  2  4   9        2    java

In [ ]:
num=3
df.query(f'b>{num}')

   a  b   c  d clmns       e
0  1  6  10        3  python
1  2  4   9        2    java

In [ ]:
s="e.str.contains('py')"
df.query(s)

   a  b   c  d clmns       e
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [ ]:
s='e.str.startswith("g")'
df.query(s)

   a  b  c  d clmns   e
3  4  0  7        0  go

In [ ]:
s="e.str.endswith('on')"
df.query(s)

   a  b   c  d clmns       e
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python